# Generated by Django 4.2.2 on 2023-07-02 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='products',
            field=models.ManyToManyField(default=None, related_name='related_categories', to='product.products'),
        ),
    ]
