# Generated by Django 4.2.2 on 2023-07-02 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_category_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='products',
            field=models.ManyToManyField(null=True, related_name='related_categories', to='product.products'),
        ),
    ]
